interface Platform {
	name: string;
	id: number;
	slug: string;
	games: Game[];
}

export interface Game {
	id: number;
	name: string;
}

const platforms: Platform[] = [
	{
		name: 'Atari Jaguar',
		id: 112,
		slug: 'atari-jaguar',
		games: [
			{ id: 817977, name: 'Alien vs Predator' },
			{ id: 30059, name: 'Tempest 2000' },
			{ id: 52884, name: 'Doom' },
			{ id: 5463, name: 'Rayman' },
			{ id: 53044, name: 'Iron Soldier' },
			{ id: 974490, name: 'Kasumi Ninja' },
			{ id: 4005, name: 'Wolfenstein 3D' },
		],
	},
	{
		name: 'Microsoft Xbox',
		id: 80,
		slug: 'microsoft-xbox',
		games: [
			{ id: 37130, name: 'Halo 2' },
			{ id: 28448, name: 'Halo: Combat Evolved' },
			{ id: 19646, name: 'Tom Clancys Splinter Cell' },
			{ id: 19635, name: 'Fable' },
			{ id: 13820, name: 'The Elder Scrolls III: Morrowind' },
			{ id: 430, name: 'Grand Theft Auto III & Vice City Bundle' },
			{ id: 53446, name: 'Need for Speed Underground 2' },
			{ id: 15859, name: 'Star Wars: Knights of the Old Republic' },
			{ id: 330722, name: 'Project Gotham Racing' },
			{ id: 286479, name: 'Dead or Alive 3' },
		],
	},
	{
		name: 'Microsoft Xbox 360',
		id: 14,
		slug: 'microsoft-xbox-360',
		games: [
			{ id: 11276, name: 'Call of Duty: Modern Warfare 3' },
			{ id: 29089, name: 'Kinect Adventures!' },
			{ id: 865, name: 'Call of Duty: Black Ops' },
			{ id: 4527, name: 'Call of Duty: Modern Warfare 2' },
			{ id: 3498, name: 'Grand Theft Auto V' },
			{ id: 28589, name: 'Halo 3' },
			{ id: 41462, name: 'FIFA 13' },
			{ id: 28632, name: 'Gears of War 3' },
			{ id: 28447, name: 'Kinect Sports' },
			{ id: 22509, name: 'Minecraft: Xbox 360 Edition' },
		],
	},
	{
		name: 'Microsoft Xbox One',
		id: 1,
		slug: 'microsoft-xbox-one',
		games: [
			{ id: 3498, name: 'Grand Theft Auto V' },
			{ id: 906, name: 'Call of Duty: Black Ops III' },
			{ id: 887, name: 'Call of Duty: Infinite Warfare' },
			{ id: 21924, name: 'Call of Duty: WWII' },
			{ id: 28126, name: 'FIFA 18' },
			{ id: 28, name: 'Red Dead Redemption 2' },
			{ id: 881, name: 'Forza Horizon 3' },
			{ id: 22509, name: 'Minecraft: Xbox One Edition' },
			{ id: 5562, name: 'Fallout 4' },
			{ id: 8444, name: 'Halo 5' },
		],
	},
	{
		name: 'Microsoft Xbox Series X/S',
		id: 186,
		slug: 'microsoft-xbox-series-x-s',
		games: [
			{ id: 326243, name: 'Elden Ring' },
			{ id: 791636, name: 'Call of Duty: Modern Warfare II' },
			{ id: 823549, name: 'FIFA 23' },
			{ id: 58779, name: 'Starfield' },
			{ id: 962679, name: 'Madden NFL 24' },
			{ id: 58751, name: 'Halo Infinite' },
			{ id: 647552, name: 'Call of Duty: Vanguard' },
			{ id: 801512, name: 'Minecraft Legends' },
			{ id: 3498, name: 'Grand Theft Auto V' },
			{ id: 47137, name: 'Fortnite' },
		],
	},
	{
		name: 'Neo Geo',
		id: 12,
		slug: 'neo-geo',
		games: [
			{ id: 14948, name: 'Metal Slug' },
			{ id: 7450, name: 'The King of Fighters 97' },
			{ id: 5970, name: 'Samurai Shodown II' },
			{ id: 54260, name: 'Fatal Fury Special' },
			{ id: 952547, name: 'Art of Fighting 3' },
			{ id: 816305, name: 'SNK vs. Capcom: The Match of the Millennium' },
			{ id: 455555, name: 'Last Resort' },
			{ id: 2225, name: 'Blazing Star' },
			{ id: 54306, name: 'Sengoku' },
			{ id: 14950, name: 'Shock Troopers' },
		],
	},
	{
		name: 'NES',
		id: 49,
		slug: 'nes',
		games: [
			{ id: 25080, name: 'Super Mario Bros' },
			{ id: 24030, name: 'Super Mario Bros. 3' },
			{ id: 259781, name: 'Tetris' },
			{ id: 25173, name: 'Super Mario Bros 2' },
			{ id: 24072, name: 'The Legend of Zelda' },
			{ id: 27168, name: 'Dr. Mario' },
			{ id: 53205, name: 'Zelda II: The Adventure of Link' },
			{ id: 54821, name: 'Dragon Quest III' },
			{ id: 48626, name: 'Dragon Quest IV' },
			{ id: 24138, name: 'Metroid' },
		],
	},
	{
		name: 'Nintendo 3DS',
		id: 8,
		slug: 'nintendo-3ds',
		games: [
			{ id: 27312, name: 'Pokémon X & Y' },
			{ id: 23748, name: 'Pokémon Sun & Moon' },
			{ id: 27970, name: 'Mario Kart 7' },
			{ id: 27159, name: 'New Super Mario Bros. 2' },
			{ id: 27102, name: 'Super Mario 3D Land' },
			{ id: 27953, name: 'Animal Crossing: New Leaf' },
			{ id: 335356, name: 'Pokémon Omega Ruby & Alpha Sapphire' },
			{ id: 27969, name: 'The Legend of Zelda: Ocarina of Time 3D' },
			{ id: 27980, name: 'Tomodachi Life' },
		],
	},
	{
		name: 'Nintendo 64',
		id: 83,
		slug: 'nintendo-64',
		games: [
			{ id: 54528, name: 'Super Mario 64' },
			{ id: 54435, name: 'Mario Kart 64' },
			{ id: 54403, name: 'GoldenEye 007' },
			{ id: 25097, name: 'The Legend of Zelda: Ocarina of Time' },
			{ id: 54531, name: 'Super Smash Bros.' },
			{ id: 54520, name: 'Star Fox 64' },
			{ id: 54380, name: 'Donkey Kong 64' },
			{ id: 54481, name: 'Pokémon Stadium' },
			{ id: 25178, name: 'Paper Mario' },
			{ id: 28532, name: 'Banjo-Kazooie' },
		],
	},
	{
		name: 'Nintendo DS',
		id: 9,
		slug: 'nintendo-ds',
		games: [
			{ id: 24933, name: 'New Super Mario Bros.' },
			{ id: 244735, name: 'Nintendogs' },
			{ id: 23943, name: 'Mario Kart DS' },
			{ id: 24934, name: 'Brain Age: Train Your Brain in Minutes a Day!' },
			{ id: 25131, name: 'Pokémon Diamond & Pearl' },
			{ id: 330615, name: 'Pokémon Black & White' },
			{ id: 23849, name: 'Animal Crossing: Wild World' },
			{ id: 25001, name: 'Tetris DS' },
			{ id: 23860, name: 'Super Mario 64 DS' },
		],
	},
	{
		name: 'Nintendo Game Boy',
		id: 26,
		slug: 'nintendo-game-boy',
		games: [
			{ id: 52623, name: 'Tetris' },
			{ id: 23762, name: 'Pokemon Red/Blue' },
			{ id: 55637, name: 'Super Mario Land' },
			{ id: 27068, name: 'Game & Watch Gallery 2' },
			{ id: 26545, name: 'The Legend of Zelda: Links Awakening' },
			{ id: 27168, name: 'Dr. Mario' },
			{ id: 52512, name: 'Donkey Kong' },
			{ id: 55278, name: 'Kirbys Dream Land' },
			{ id: 27150, name: 'Wario Land: Super Mario Land 3' },
			{ id: 24151, name: 'Metroid II: Return of Samus' },
		],
	},
	{
		name: 'Nintendo Game Boy Advance',
		id: 24,
		slug: 'nintendo-game-boy-advance',
		games: [
			{ id: 4890, name: 'Pokémon Ruby & Sapphire' },
			{ id: 4891, name: 'Pokémon FireRed & LeafGreen' },
			{ id: 23981, name: 'Super Mario Advance' },
			{ id: 2881, name: 'Mario Kart: Super Circuit' },
			{ id: 2845, name: 'Takara Tomy’s Mario Party Advance' },
			{ id: 2247, name: 'Super Mario World: Super Mario Advance 2' },
			{ id: 4866, name: 'WarioWare, Inc.: Mega Microgame$!' },
			{ id: 25042, name: 'Metroid Fusion' },
			{ id: 2579, name: 'The Legend of Zelda: A Link to the Past & Four Swords' },
			{ id: 4892, name: 'Pokémon Emerald' },
		],
	},
	{
		name: 'Nintendo Game Boy Color',
		id: 43,
		slug: 'nintendo-game-boy-color',
		games: [
			{ id: 27936, name: 'Pokémon Gold & Silver' },
			{ id: 50971, name: 'Pokémon Crystal' },
			{ id: 27256, name: 'The Legend of Zelda: Oracle of Ages' },
			{ id: 27255, name: 'The Legend of Zelda: Oracle of Seasons' },
			{ id: 993429, name: 'Pokémon Yellow' },
			{ id: 54873, name: 'Pokémon Trading Card Game' },
			{ id: 23970, name: 'Super Mario Bros. Deluxe' },
			{ id: 975827, name: 'Mario Tennis' },
			{ id: 27213, name: 'Wario Land II' },
		],
	},
	{
		name: 'Nintendo GameCube',
		id: 105,
		slug: 'nintendo-gamecube',
		games: [
			{ id: 56222, name: 'Super Smash Bros. Melee' },
			{ id: 56097, name: 'Mario Kart: Double Dash!!' },
			{ id: 56092, name: 'The Legend of Zelda: The Wind Waker' },
			{ id: 52371, name: 'Super Mario Sunshine' },
			{ id: 52312, name: 'Luigis Mansion' },
			{ id: 56123, name: 'Metroid Prime' },
			{ id: 54346, name: 'Animal Crossing' },
			{ id: 56174, name: 'Pokémon Colosseum' },
			{ id: 53729, name: 'Resident Evil 4' },
			{ id: 24239, name: 'Pikmin 2' },
		],
	},
	{
		name: 'Nintendo Switch',
		id: 7,
		slug: 'nintendo-switch',
		games: [
			{ id: 23165, name: 'Mario Kart 8 Deluxe' },
			{ id: 421698, name: 'Animal Crossing: New Horizons' },
			{ id: 58829, name: 'Super Smash Bros. Ultimate' },
			{ id: 22511, name: 'The Legend of Zelda: Breath of the Wild' },
			{ id: 282825, name: 'Pokémon Sword & Shield' },
			{ id: 28026, name: 'Super Mario Odyssey' },
			{ id: 747505, name: 'Pokémon Scarlet & Violet' },
			{ id: 28024, name: 'Splatoon 2' },
			{ id: 236697, name: "Luigi's Mansion 3" },
			{ id: 292840, name: 'Super Mario Maker 2' },
		],
	},
	{
		name: 'Nintendo Switch 2',
		id: 7,
		slug: 'nintendo-switch-2',
		games: [
			{ id: 1000574, name: 'Mario Kart World' },
			{ id: 1000582, name: 'Donkey Kong Bonanza' },
			{ id: 41494, name: 'Cyberpunk 2077: Ultimate Edition' },
			{ id: 327239, name: 'The Legend of Zelda: Tears of the Kingdom' },
			{ id: 989033, name: 'Super Marion Party Jamboree' },
			{ id: 667657, name: 'Kirby and the Forgotten Land' },
			{ id: 1000197, name: 'Pokemon Legends Z-A' },
			{ id: 906547, name: 'Hogwarts Legacy' },
			{ id: 931660, name: 'Fantasy Life i: The Girl Who Steals Time' },
		],
	},
	{
		name: 'Nintendo Wii',
		id: 11,
		slug: 'nintendo-wii',
		games: [
			{ id: 25057, name: 'Wii Sports' },
			{ id: 24761, name: 'Mario Kart Wii' },
			{ id: 26002, name: 'Wii Sports Resort' },
			{ id: 25414, name: 'Super Smash Bros. Brawl' },
			{ id: 734626, name: 'New Super Mario Bros. Wii' },
			{ id: 26193, name: 'Wii Play' },
			{ id: 26193, name: 'Just Dance' },
			{ id: 25482, name: 'Wii Fit' },
			{ id: 24875, name: 'Pokémon Battle Revolution' },
			{ id: 27024, name: 'Super Mario Galaxy' },
		],
	},
	{
		name: 'Nintendo Wii U',
		id: 10,
		slug: 'nintendo-wii-u',
		games: [
			{ id: 27976, name: 'Mario Kart 8' },
			{ id: 27967, name: 'New Super Mario Bros. U' },
			{ id: 23763, name: 'Super Smash Bros. for Wii U' },
			{ id: 23935, name: 'Splatoon' },
			{ id: 27974, name: 'Super Mario 3D World' },
			{ id: 22511, name: 'The Legend of Zelda: Breath of the Wild' },
			{ id: 27978, name: 'Donkey Kong Country: Tropical Freeze' },
			{ id: 27973, name: 'Pikmin 3' },
			{ id: 23760, name: 'Bayonetta 2' },
			{ id: 27196, name: 'Nintendo Land' },
		],
	},
	{
		name: 'Panasonic 3DO',
		id: 111,
		slug: 'panasonic-3do',
		games: [
			{ id: 5170, name: 'Gex' },
			{ id: 31321, name: 'Road Rash' },
			{ id: 32929, name: 'Super Street Fighter 2 Turbo' },
			{ id: 30948, name: 'Return Fire' },
			{ id: 22708, name: 'Wing Commander III' },
			{ id: 31235, name: 'The Need for Speed' },
			{ id: 30644, name: 'The Horde' },
		],
	},
	{
		name: 'Sega 32X',
		id: 117,
		slug: 'sega-32x',
		games: [
			{ id: 55194, name: 'Virtua Racing Deluxe' },
			{ id: 55193, name: 'Virtua Fighter' },
			{ id: 55179, name: 'Knuckles Chaotix' },
			{ id: 55183, name: 'Metal Head' },
			{ id: 55181, name: 'Kolibri' },
			{ id: 55190, name: 'Tempo' },
			{ id: 55187, name: 'Star Wars Arcade' },
			{ id: 54174, name: 'After Burner Complete' },
			{ id: 55186, name: 'The Amazing Spider Man: Web of Fire' },
		],
	},
	{
		name: 'Sega CD',
		id: 119,
		slug: 'sega-cd',
		games: [
			{ id: 1559, name: 'Sonic CD' },
			{ id: 54318, name: 'Snatcher' },
			{ id: 54275, name: 'Lunar: The Silver Star' },
			{ id: 53291, name: 'Final Fight CD' },
			{ id: 54315, name: 'Shining Force CD' },
			{ id: 54293, name: 'Popful Mail' },
			{ id: 54255, name: 'Ecco the Dolphin' },
			{ id: 54301, name: 'Robo Aleste' },
			{ id: 54288, name: 'Night Trap' },
		],
	},
	{
		name: 'Sega Dreamcast',
		id: 106,
		slug: 'sega-dreamcast',
		games: [
			{ id: 343595, name: 'Sonic Adventure' },
			{ id: 328000, name: 'Soul Calibur' },
			{ id: 51673, name: 'Shenmue' },
			{ id: 40841, name: 'Resident Evil - Code: Veronica' },
			{ id: 54629, name: 'Crazy Taxi' },
			{ id: 343597, name: 'Sonic Adventure 2' },
			{ id: 32575, name: 'Tony Hawks Pro Skater 2' },
			{ id: 54780, name: 'Virtua Fighter 3tb' },
			{ id: 30559, name: 'Sega Rally 2' },
			{ id: 53341, name: 'Jet Set Radio' },
		],
	},
	{
		name: 'Sega Genesis',
		id: 167,
		slug: 'sega-genesis',
		games: [
			{ id: 53551, name: 'Sonic the Hedgehog' },
			{ id: 2552, name: 'Sonic the Hedgehog 2' },
			{ id: 54285, name: 'Mortal Kombat' },
			{ id: 57189, name: 'Street Fighter II: Special Champion Edition' },
			{ id: 54286, name: 'NBA Jam' },
			{ id: 19249, name: 'Ecco the Dolphin' },
			{ id: 53239, name: 'Aladdin' },
			{ id: 4648, name: 'Golden Axe' },
			{ id: 57173, name: 'Shinobi III: Return of the Ninja Master' },
			{ id: 25663, name: 'Earthworm Jim' },
		],
	},
	{
		name: 'Sega Master System',
		id: 74,
		slug: 'sega-master-system',
		games: [
			{ id: 4364, name: 'Alex Kidd in Miracle World' },
			{ id: 884680, name: 'Sonic the Hedgehog' },
			{ id: 26035, name: 'Phantasy Star' },
			{ id: 127688, name: 'Wonder Boy III: The Dragons Trap' },
			{ id: 54198, name: 'Fantasy Zone' },
			{ id: 3802, name: 'Double Dragon' },
			{ id: 24742, name: 'Chase HQ' },
			{ id: 54174, name: 'After Burner' },
			{ id: 55084, name: 'Out Run' },
		],
	},
	{
		name: 'Sega Saturn',
		id: 107,
		slug: 'sega-saturn',
		games: [
			{ id: 57244, name: 'Virtua Fighter 2' },
			{ id: 28300, name: 'NiGHTS into Dreams' },
			{ id: 53520, name: 'Sega Rally Championship' },
			{ id: 31098, name: 'Panzer Dragoon' },
			{ id: 4564, name: 'Daytona USA' },
			{ id: 14948, name: 'Metal Slug' },
			{ id: 331123, name: 'Guardian Heroes' },
			{ id: 54318, name: 'Snatcher' },
			{ id: 10325, name: 'Soulcalibur' },
			{ id: 53570, name: 'Street Fighter Alpha 3' },
		],
	},
	{
		name: 'Sony PlayStation',
		id: 27,
		slug: 'sony-playstation',
		games: [
			{ id: 52995, name: 'Gran Turismo' },
			{ id: 52939, name: 'Final Fantasy VII' },
			{ id: 57607, name: 'Metal Gear Solid' },
			{ id: 57842, name: 'Tekken 3' },
			{ id: 32575, name: 'Tony Hawks Pro Skater 2' },
			{ id: 5488, name: 'Crash Bandicoot' },
			{ id: 52825, name: 'Crash Team Racing' },
			{ id: 31759, name: 'Tomb Raider' },
			{ id: 52790, name: 'Castlevania: Symphony of the Night' },
			{ id: 5159, name: 'Resident Evil 2' },
		],
	},
	{
		name: 'Sony PlayStation 2',
		id: 15,
		slug: 'sony-playstation-2',
		games: [
			{ id: 416, name: 'Grand Theft Auto: San Andreas' },
			{ id: 311655, name: 'Gran Turismo 3: A-Spec' },
			{ id: 430, name: 'Grand Theft Auto: Vice City' },
			{ id: 59132, name: 'Gran Turismo 4' },
			{ id: 432, name: 'Grand Theft Auto III' },
			{ id: 29179, name: 'God of War' },
			{ id: 52335, name: 'Guitar Hero II' },
			{ id: 4283, name: 'Ratchet & Clank: Up Your Arsenal' },
			{ id: 30990, name: 'Madden NFL 2003' },
		],
	},
	{
		name: 'Sony PlayStation 3',
		id: 16,
		slug: 'sony-playstation-3',
		games: [
			{ id: 39080, name: 'Gran Turismo 5' },
			{ id: 3990, name: 'The Last of Us' },
			{ id: 22513, name: 'Uncharted 2: Among Thieves' },
			{ id: 5703, name: 'Uncharted 3: Drakes Deception' },
			{ id: 3469, name: 'Metal Gear Solid 4: Guns of the Patriots' },
			{ id: 28623, name: 'Batman: Arkham City' },
			{ id: 4544, name: 'Red Dead Redemption' },
			{ id: 3179, name: 'LittleBigPlanet' },
			{ id: 4527, name: 'Call of Duty: Modern Warfare 2' },
		],
	},
	{
		name: 'Sony PlayStation 4',
		id: 18,
		slug: 'sony-playstation-4',
		games: [
			{ id: 3498, name: 'Grand Theft Auto V' },
			{ id: 21924, name: 'Call of Duty: WWII' },
			{ id: 906, name: 'Call of Duty: Black Ops III' },
			{ id: 1249, name: 'FIFA 17' },
			{ id: 28126, name: 'FIFA 18' },
			{ id: 58134, name: 'Spider-Man' },
			{ id: 46070, name: 'Red Dead Redemption 2' },
			{ id: 281541, name: 'God of War' },
			{ id: 22509, name: 'Minecraft' },
			{ id: 51325, name: 'The Last of Us Part II' },
		],
	},
	{
		name: 'Sony PlayStation 5',
		id: 187,
		slug: 'sony-playstation-5',
		games: [
			{ id: 326243, name: 'Elden Ring' },
			{ id: 791636, name: 'Call of Duty: Modern Warfare II' },
			{ id: 494384, name: 'God of War Ragnarök' },
			{ id: 662316, name: 'Spider-Man 2' },
			{ id: 452642, name: 'Horizon Forbidden West' },
			{ id: 823549, name: 'FIFA 23' },
			{ id: 452633, name: 'Gran Turismo 7' },
			{ id: 452634, name: 'Marvels Spider-Man: Miles Morales' },
			{ id: 452649, name: 'Resident Evil Village' },
			{ id: 41494, name: 'Cyberpunk 2077' },
		],
	},
	{
		name: 'Super Nintendo Entertainment System (SNES)',
		id: 79,
		slug: 'super-nintendo-entertainment-system-snes',
		games: [
			{ id: 24899, name: 'Super Mario World' },
			{ id: 57518, name: 'Super Mario All-Stars' },
			{ id: 27571, name: 'Donkey Kong Country' },
			{ id: 24478, name: 'Super Mario Kart' },
			{ id: 55132, name: 'Street Fighter II: The World Warrior' },
			{ id: 25096, name: 'The Legend of Zelda: A Link to the Past' },
			{ id: 27022, name: 'Super Metroid' },
			{ id: 1063, name: 'Final Fantasy VI' },
			{ id: 24918, name: 'F-Zero' },
			{ id: 52800, name: 'Chrono Trigger' },
		],
	},
	/*{
		name: 'TurboGrafx-16' },
		id: 35,
		slug: 'turbografx-16' },
		games: [
			{ id: , name: 'Bonks Adventure' },
			{ id: , name: 'Bonks Revenge' },
			{ id: , name: 'Bomberman 93' },
			{ id: , name: 'Ys Book I & II' },
			{ id: , name: 'Blazing Lazers' },
			{ id: , name: 'Splatterhouse' },
			{ id: , name: 'Keith Courage in Alpha Zones' },
			{ id: , name: 'Alien Crush' },
			{ id: , name: 'R-Type' },
			{ id: , name: 'Ninja Spirit' },
		],
	},*/
];

export default platforms;
