interface Platform {
	name: string;
	id: number;
	slug: string;
	games: string[];
}

const platforms: Platform[] = [
	{
		name: 'Atari Jaguar',
		id: 112,
		slug: 'atari-jaguar',
		games: [
			'Alien vs Predator',
			'Tempest 2000',
			'Doom',
			'Rayman',
			'Cybermorph',
			'Iron Soldier',
			'Trevor McFur in the Crescent Galaxy',
			'Kasumi Ninja',
			'Wolfenstein 3D',
			'Super Burnout',
		],
	},
	{
		name: 'Microsoft Xbox',
		id: 80,
		slug: 'microsoft-xbox',
		games: [
			'Halo 2',
			'Halo: Combat Evolved',
			'Tom Clancy’s Splinter Cell',
			'Fable',
			'The Elder Scrolls III: Morrowind',
			'Grand Theft Auto III & Vice City Bundle',
			'Need for Speed Underground 2',
			'Star Wars: Knights of the Old Republic',
			'Project Gotham Racing',
			'Dead or Alive 3',
		],
	},
	{
		name: 'Microsoft Xbox 360',
		id: 14,
		slug: 'microsoft-xbox-360',
		games: [
			'Call of Duty: Modern Warfare 3',
			'Kinect Adventures!',
			'Call of Duty: Black Ops',
			'Call of Duty: Modern Warfare 2',
			'Grand Theft Auto V',
			'Halo 3',
			'FIFA 13',
			'Gears of War 3',
			'Kinect Sports',
			'Minecraft: Xbox 360 Edition',
		],
	},
	{
		name: 'Microsoft Xbox One',
		id: 1,
		slug: 'microsoft-xbox-one',
		games: [
			'Grand Theft Auto V',
			'Call of Duty: Black Ops III',
			'Call of Duty: Infinite Warfare',
			'Call of Duty: WWII',
			'FIFA 18',
			'Red Dead Redemption 2',
			'Forza Horizon 3',
			'Minecraft: Xbox One Edition',
			'FIFA 17',
			'FIFA 19',
		],
	},
	{
		name: 'Microsoft Xbox Series X/S',
		id: 186,
		slug: 'microsoft-xbox-series-x-s',
		games: [
			'Elden Ring',
			'Call of Duty: Modern Warfare II',
			'FIFA 23',
			'Starfield',
			'Madden NFL 23',
			'Halo Infinite',
			'Call of Duty: Vanguard',
			'Minecraft',
			'Grand Theft Auto V',
			'Fortnite',
		],
	},
	{
		name: 'Neo Geo AES',
		id: 12,
		slug: 'neo-geo-aes',
		games: [
			'Metal Slug',
			'The King of Fighters 98',
			'Samurai Shodown II',
			'Fatal Fury Special',
			'Art of Fighting 2',
			'Magician Lord',
			'Last Blade',
			'Blazing Star',
			'Sengoku',
			'Shock Troopers',
		],
	},
	{
		name: 'Nintendo 3DS',
		id: 8,
		slug: 'nintendo-3ds',
		games: [
			'Pokémon X & Y',
			'Pokémon Sun & Moon',
			'Mario Kart 7',
			'New Super Mario Bros. 2',
			'Super Mario 3D Land',
			'Animal Crossing: New Leaf',
			'Pokémon Omega Ruby & Alpha Sapphire',
			'The Legend of Zelda: Ocarina of Time 3D',
			'Mario Kart 8 Deluxe (3DS version title varies)',
			'Tomodachi Life',
		],
	},
	{
		name: 'Nintendo 64',
		id: 83,
		slug: 'nintendo-64',
		games: [
			'Super Mario 64',
			'Mario Kart 64',
			'GoldenEye 007',
			'The Legend of Zelda: Ocarina of Time',
			'Super Smash Bros.',
			'Lylat Wars (Star Fox 64)',
			'Donkey Kong 64',
			'Pokémon Stadium',
			'Paper Mario',
			'Banjo-Kazooie',
		],
	},
	{
		name: 'Nintendo DS',
		id: 9,
		slug: 'nintendo-ds',
		games: [
			'New Super Mario Bros.',
			'Nintendogs',
			'Mario Kart DS',
			'Brain Age: Train Your Brain in Minutes a Day!',
			'Pokémon Diamond & Pearl',
			'Pokémon Black & White',
			'Animal Crossing: Wild World',
			'Wii Play (included DS version for bundle)',
			'Tetris DS',
			'Super Mario 64 DS',
		],
	},
	{
		name: 'Nintendo Game Boy',
		id: 26,
		slug: 'nintendo-game-boy',
		games: [
			'Tetris',
			'Pokémon Red/Blue',
			'Super Mario Land',
			'Game & Watch Gallery 2',
			'The Legend of Zelda: Link’s Awakening',
			'Dr. Mario',
			'Donkey Kong',
			'Kirby’s Dream Land',
			'Wario Land: Super Mario Land 3',
			'Metroid II: Return of Samus',
		],
	},
	{
		name: 'Nintendo Game Boy Advance',
		id: 24,
		slug: 'nintendo-game-boy-advance',
		games: [
			'Pokémon Ruby & Sapphire',
			'Pokémon FireRed & LeafGreen',
			'Super Mario Advance',
			'Mario Kart: Super Circuit',
			'Takara Tomy’s Mario Party Advance',
			'Super Mario World: Super Mario Advance 2',
			'WarioWare, Inc.: Mega Microgame$!',
			'Metroid Fusion',
			'The Legend of Zelda: A Link to the Past & Four Swords',
			'Pokémon Emerald',
		],
	},
	{
		name: 'Nintendo Game Boy Color',
		id: 43,
		slug: 'nintendo-game-boy-color',
		games: [
			'Pokémon Gold & Silver',
			'Pokémon Crystal',
			'The Legend of Zelda: Oracle of Ages',
			'The Legend of Zelda: Oracle of Seasons',
			'Pokémon Yellow',
			'Tetris DX',
			'Pokémon Trading Card Game',
			'Super Mario Bros. Deluxe',
			'Mario Tennis',
			'Wario Land II',
		],
	},
	{
		name: 'Nintendo GameCube',
		id: 105,
		slug: 'nintendo-gamecube',
		games: [
			'Super Smash Bros. Melee',
			'Mario Kart: Double Dash!!',
			'The Legend of Zelda: The Wind Waker',
			'Super Mario Sunshine',
			'Luigis Mansion',
			'Metroid Prime',
			'Animal Crossing',
			'Pokémon Colosseum',
			'Resident Evil 4',
			'Pikmin 2',
		],
	},
	{
		name: 'Nintendo Switch',
		id: 7,
		slug: 'nintendo-switch',
		games: [
			'Mario Kart 8 Deluxe',
			'Animal Crossing: New Horizons',
			'Super Smash Bros. Ultimate',
			'The Legend of Zelda: Breath of the Wild',
			'Pokémon Sword & Shield',
			'Super Mario Odyssey',
			'Pokémon Scarlet & Violet',
			'Splatoon 2',
			'Luigis Mansion 3',
			'Super Mario Maker 2',
		],
	},
	{
		name: 'Nintendo Switch 2',
		id: 7,
		slug: 'nintendo-switch-2',
		games: [
			'Mario Kart World',
			'Donkey Kong Bonanza',
			'Cyberpunk 2077: Ultimate Edition',
			'The Legend of Zelda: Tears of the Kingdom',
			'Super Marion Party Jamboree',
			'Kirby and the Forgotten Land',
			'Pokemon Legends Z-A',
			'Hogwarts Legacy',
			'Street Figher 6 Years 1-2 Fighters Edition',
			'Fantasy Life i: The Girl Who Steals Time',
		],
	},
	{
		name: 'Nintendo Wii',
		id: 11,
		slug: 'nintendo-wii',
		games: [
			'Wii Sports',
			'Mario Kart Wii',
			'Wii Sports Resort',
			'Super Smash Bros. Brawl',
			'New Super Mario Bros. Wii',
			'Wii Play',
			'Just Dance',
			'Wii Fit',
			'Pokémon Battle Revolution',
			'Super Mario Galaxy',
		],
	},
	{
		name: 'Nintendo Wii U',
		id: 10,
		slug: 'nintendo-wii-u',
		games: [
			'Mario Kart 8',
			'New Super Mario Bros. U',
			'Super Smash Bros. for Wii U',
			'Splatoon',
			'Super Mario 3D World',
			'The Legend of Zelda: Breath of the Wild',
			'Donkey Kong Country: Tropical Freeze',
			'Pikmin 3',
			'Bayonetta 2',
			'Nintendo Land',
		],
	},
	{
		name: 'Panasonic 3DO',
		id: 111,
		slug: 'panasonic-3do',
		games: [
			'Gex',
			'Road Rash',
			'Star Fighter 3000',
			'Return Fire',
			'Wing Commander III',
			'The Need for Speed',
			'Lone Soldier',
			'Crash n Burn',
			'Jurassic Park Interactive',
			'The Horde',
		],
	},
	{
		name: 'Sega CD',
		id: 119,
		slug: 'sega-cd',
		games: [
			'Sonic CD',
			'Snatcher',
			'Lunar: The Silver Star',
			'Lunar 2: Eternal Blue',
			'Final Fight CD',
			'Shining Force CD',
			'Popful Mail',
			'Ecco the Dolphin',
			'Robo Aleste',
			'Night Trap',
		],
	},
	{
		name: 'Sega Genesis',
		id: 167,
		slug: 'sega-genesis',
		games: [
			'Sonic the Hedgehog',
			'Sonic the Hedgehog 2',
			'Mortal Kombat',
			'Street Fighter II: Special Champion Edition',
			'NBA Jam',
			'Ecco the Dolphin',
			'Aladdin',
			'Golden Axe',
			'Shinobi III: Return of the Ninja Master',
			'Earthworm Jim',
		],
	},
	{
		name: 'Sega Master System',
		id: 74,
		slug: 'sega-master-system',
		games: [
			'Alex Kidd in Miracle World',
			'Sonic the Hedgehog',
			'Phantasy Star',
			'Wonder Boy III: The Dragons Trap',
			'Fantasy Zone',
			'Double Dragon',
			'Star Wars: The Empire Strikes Back',
			'Chase HQ',
			'After Burner',
			'Out Run',
		],
	},
	{
		name: 'Sega Saturn',
		id: 107,
		slug: 'sega-saturn',
		games: [
			'Virtua Fighter 2',
			'Nights into Dreams...',
			'Sega Rally Championship',
			'Panzer Dragoon',
			'Daytona USA',
			'Metal Slug',
			'Guardian Heroes',
			'Snatcher',
			'Soulcalibur',
			'Street Fighter Alpha 3',
		],
	},
	{
		name: 'Sony PlayStation',
		id: 27,
		slug: 'sony-playstation',
		games: [
			'Gran Turismo',
			'Final Fantasy VII',
			'Metal Gear Solid',
			'Tekken 3',
			'Tony Hawks Pro Skater 2',
			'Crash Bandicoot',
			'Crash Team Racing',
			'Tomb Raider',
			'Castlevania: Symphony of the Night',
			'Resident Evil 2',
		],
	},
	{
		name: 'Sony PlayStation 2',
		id: 15,
		slug: 'sony-playstation-2',
		games: [
			'Grand Theft Auto: San Andreas',
			'Gran Turismo 3: A-Spec',
			'Grand Theft Auto: Vice City',
			'Gran Turismo 4',
			'Grand Theft Auto III',
			'Pro Evolution Soccer 3',
			'God of War',
			'Guitar Hero II',
			'Ratchet & Clank: Up Your Arsenal',
			'Madden NFL 2003',
		],
	},
	{
		name: 'Sony PlayStation 3',
		id: 16,
		slug: 'sony-playstation-3',
		games: [
			'Grand Theft Auto V',
			'Gran Turismo 5',
			'The Last of Us',
			'Uncharted 2: Among Thieves',
			'Uncharted 3: Drakes Deception',
			'Metal Gear Solid 4: Guns of the Patriots',
			'Batman: Arkham City',
			'Red Dead Redemption',
			'LittleBigPlanet',
			'Call of Duty: Modern Warfare 2',
		],
	},
	{
		name: 'Sony PlayStation 4',
		id: 18,
		slug: 'sony-playstation-4',
		games: [
			'Grand Theft Auto V',
			'Call of Duty: WWII',
			'Call of Duty: Black Ops III',
			'FIFA 17',
			'FIFA 18',
			'Spider-Man',
			'Red Dead Redemption 2',
			'God of War',
			'Minecraft',
			'The Last of Us Part II',
		],
	},
	{
		name: 'Sony PlayStation 5',
		id: 187,
		slug: 'sony-playstation-5',
		games: [
			'Elden Ring',
			'Call of Duty: Modern Warfare II',
			'God of War Ragnarök',
			'Spider-Man 2',
			'Horizon Forbidden West',
			'FIFA 23',
			'Gran Turismo 7',
			'Marvels Spider-Man: Miles Morales',
			'Resident Evil Village',
			'Cyberpunk 2077',
		],
	},
	{
		name: 'Super Nintendo Entertainment System (SNES)',
		id: 79,
		slug: 'super-nintendo-entertainment-system-snes',
		games: [
			'Super Mario World',
			'Super Mario All-Stars',
			'Donkey Kong Country',
			'Super Mario Kart',
			'Street Fighter II: The World Warrior',
			'The Legend of Zelda: A Link to the Past',
			'Super Metroid',
			'Final Fantasy VI',
			'F-Zero',
			'Chrono Trigger',
		],
	},
	/*{
		name: 'TurboGrafx-16',
		id: 35,
		slug: 'turbografx-16',
		games: [
			'Bonks Adventure',
			'Bonks Revenge',
			'Bomberman 93',
			'Ys Book I & II',
			'Blazing Lazers',
			'Splatterhouse',
			'Keith Courage in Alpha Zones',
			'Alien Crush',
			'R-Type',
			'Ninja Spirit',
		],
	},*/
];

export default platforms;
